site_name: My Docs
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: Why would you like to burn your eyes?

    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode